// reportFormatter.js

/**
 * 분석 결과를 Slack 메시지 형식으로 포맷합니다.
 */
function formatDailyReport(analysisResult, repoInfo) {
  if (!analysisResult) {
    return "일일 보고서 생성 중 오류가 발생했습니다.";
  }

  const today = new Date().toLocaleDateString("ko-KR", {
    year: "numeric",
    month: "long",
    day: "numeric",
    weekday: "long",
  });

  const header = `📊 *일일 개발 보고서*\n📅 ${today}\n📁 ${repoInfo.owner}/${repoInfo.repo}\n${"─".repeat(30)}`;

  const body = analysisResult.summary;

  const footer = `${"─".repeat(30)}\n🤖 Generated by Gemini AI`;

  return `${header}\n\n${body}\n\n${footer}`;
}

module.exports = { formatDailyReport };
