// reportFormatter.test.js
const {
  formatDailyReport,
} = require("../../src/daily-report/reportFormatter");

describe("reportFormatter", () => {
  const repoInfo = { owner: "testowner", repo: "testrepo" };

  test("분석 결과가 없으면 오류 메시지를 반환해야 한다", () => {
    const result = formatDailyReport(null, repoInfo);

    expect(result).toBe("일일 보고서 생성 중 오류가 발생했습니다.");
  });

  test("올바른 형식의 보고서를 생성해야 한다", () => {
    const analysisResult = {
      summary: "📝 오늘은 새로운 기능이 추가되었습니다.",
    };

    const result = formatDailyReport(analysisResult, repoInfo);

    // 헤더 확인
    expect(result).toContain("📊 *일일 개발 보고서*");
    expect(result).toContain("testowner/testrepo");

    // 본문 확인
    expect(result).toContain("📝 오늘은 새로운 기능이 추가되었습니다.");

    // 푸터 확인
    expect(result).toContain("🤖 Generated by Gemini AI");
  });

  test("날짜가 한국어 형식으로 포함되어야 한다", () => {
    const analysisResult = { summary: "테스트" };

    const result = formatDailyReport(analysisResult, repoInfo);

    // 한국어 날짜 형식 확인 (예: 2024년 1월 28일 일요일)
    expect(result).toMatch(/\d{4}년 \d{1,2}월 \d{1,2}일/);
  });
});
